---
title: "Project2Code"
author: "Eric Liang"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = F, warning = F}
library(tidyverse)
```

```{r}
orgDeaths <- read_csv("gun-violence-data.csv")
```

```{r}
gun_violence2018 <- subset(orgDeaths, substr(orgDeaths$date, 1, 4) == "2018")
gun_violence2018$state <- tolower(gun_violence2018$state)

gun_violence2018 <- mutate(gun_violence2018,
                           n_affected = as.factor(n_killed + n_injured))

gun_violence2018$n_affected <- fct_collapse(gun_violence2018$n_affected, "8+" = c("8", "16","34"))
```

```{r}
# filter out data to just one year
start_date <- as.Date("2017-03-01", format = "%Y-%m-%d")
end_date <- as.Date("2018-03-30", format = "%Y-%m-%d")
deaths <- mutate(orgDeaths, date = as.Date(date, format = "%Y-%m-%d")) %>%
  filter(date >= start_date & date <= end_date)
```

```{r}
# Pre Cleaning for Gun Types
types <- deaths$gun_type
types <- unlist(lapply(types,function(x) str_split(x,"\\|\\|")[[1]][1]))
types <- unlist(lapply(types,function(x) str_split(x,"\\|")[[1]][1]))
types <- unlist(lapply(types,function(x) gsub("::",":",x)))
reduceCat <- function(x) {
  if (grepl("gauge",x)){
    return("Shotgun")
  }
  if (grepl("Win",x)){
    return("Win")
  }
  if (grepl("Mag",x)){
    return("Mag")
  }
  if (grepl("Auto",x)){
    return("Auto")
  }
  if (grepl("10mm",x)){
    return("Handgun")
  }
  if (grepl("9mm",x)){
    return("Handgun")
  }
  if (grepl("Gauge",x)){
    return("Shotgun")
  }
  if (grepl("30-06",x)){
    return("Rifle")
  }
  if (grepl("223 Rem",x)){
    return("AR-15")
  }
  if (grepl("38 Spl",x)){
    return("Handgun")
  }
  if (grepl("40 SW",x)){
    return("Handgun")
  }
  if (grepl("AK-47",x)){
    return("AK-47")
  }
return(x)
}
types <- unlist(lapply(types,reduceCat))
types <- unlist(lapply(types,function(x) gsub("0:","",x)))
deaths$gun_type <- types
```

```{r}
# filter out data to just PA
penn_deadly_data <- filter(deaths, state == "Pennsylvania"
                           & n_killed > 0 & !is.na(latitude))
```

```{r}
age_and_type <- select(deaths, participant_age, participant_type, 
                       date, state) %>%
  filter(!is.na(participant_age) & !is.na(participant_type)) %>%
  mutate(ages = str_split(participant_age, "\\|\\|"),
         types = str_split(participant_type, "\\|\\|"))
 
num_participants <- sapply(age_and_type$ages,function(x){return(length(x))})
 
age_and_type <- mutate(age_and_type, num_participants = num_participants) %>%
  filter(num_participants > 1) %>% select(ages, types, num_participants, date, 
                                          state)
 
split_ages <-  lapply(age_and_type$ages, function(x){return(substr(x, 4, 5))})
split_types <- lapply(age_and_type$types,
                      function(x){return(substr(x, 4, nchar(x)))})
 
age_and_type <- mutate(age_and_type, ages = split_ages, types = split_types)
 
num_victims <- sapply(age_and_type$types, 
                      function(x){return(sum(x == "Victim"))})
num_suspects <- sapply(age_and_type$types, 
                       function(x){return(sum(x == "Subject-Suspect"))})
 
age_and_type <- mutate(age_and_type, num_victims = num_victims, 
                       num_suspects = num_suspects) %>%
  filter(num_victims > 0 & num_suspects > 0)
 
victim_avg_age <- rep(0, nrow(age_and_type))
suspect_avg_ages <- rep(0, nrow(age_and_type))
 
for (i in 1:nrow(age_and_type)) {
  victim_ages <- suppressWarnings(
    as.numeric(unlist(age_and_type[i,]$ages)[which(
      unlist(age_and_type[i,]$types) == "Victim")]))
  suspect_ages <- suppressWarnings(as.numeric(
    unlist(age_and_type[i,]$ages)[which(
      unlist(age_and_type[i,]$types) == "Subject-Suspect" | 
        unlist(age_and_type[i,]$types) == ":Subject-Suspect")]))
  victim_avg_age[i] <- mean(victim_ages, na.rm = TRUE)
  suspect_avg_ages[i] <- mean(suspect_ages, na.rm = TRUE)
}

age_and_type <- mutate(age_and_type, avg_victim_age = victim_avg_age, 
                       avg_suspect_age = suspect_avg_ages) %>%
  select(date, state, avg_victim_age, avg_suspect_age) %>% 
  filter(!is.na(avg_victim_age) & !is.na(suspect_avg_ages))

get_region <- function(state) {
  if (state %in% c("Maine", "New Hampshire", "Vermont", "Massachusetts", 
                   "Rhode Island", "Connecticut", "New York", "Pennsylvania", 
                   "New Jersey")) {
    return("Northeast")
  } else if (state %in% c("Wisconsin", "Michigan", "Illinois", "Indiana", 
                          "Ohio", "North Dakota", "South Dakota", "Nebraska",
                          "Kansas", "Minnesota", "Iowa", "Missouri")) {
    return("Midwest")
  } else if (state %in% c("Delaware", "Maryland", "District of Columbia",
                          "Virginia", "West Virginia", "North Carolina",
                          "South Carolina", "Georgia", "Florida",  "Kentucky",
                          "Tennessee", "Mississippi", "Alabama", "Oklahoma",
                          "Texas", "Arkansas", "Louisiana")) {
    return("South")
  } else {
    return("West")
  }
}

age_data_region <- mutate(age_and_type, region = sapply(state, get_region),
                          month = format(as.Date(date, format = "%Y-%m-%d"), 
                                         "%B %Y"))
```

```{r}
# write out the filtered data
deaths <- select(deaths,state,gun_type,notes)
write.csv(deaths,"filteredViolence.csv",row.names = FALSE)

penn_deaths <- select(penn_deadly_data,
                      n_killed,longitude,latitude,date,n_injured,source_url)
write.csv(penn_deaths,"pennDeadly.csv",row.names = FALSE)

write.csv(age_data_region,"gun-violence-ages.csv",row.names = FALSE)

injured_killed <- select(orgDeaths,date,n_injured,n_killed)
write.csv(injured_killed, "injured_killed.csv",row.names = FALSE)

violence_2018 <- select(gun_violence2018,n_guns_involved,n_affected)
write.csv(violence_2018,"violence_2018.csv",row.names = FALSE)

data_one_year <- select(deaths,n_killed,n_injured,state)
write.csv(data_one_year,"oneYear.csv",row.names = FALSE)
```

